footer_mobile
Bykova-Kateryna/project--9 pull request #2
Opened 2022-05-13 21:28 UTC by Bykova-Kateryna

2022-05-13 22:09 UTC, gdutchak requested changes

2022-05-13 22:09 UTC, gdutchak commented on src/partials/footer.html
> +      <img class="footer-logo__img" src="/svg/logo.svg" alt="logo">
незнаю наскільки добре вставляти svg через img, можливо поточни тоді у ментора)

2022-05-13 22:09 UTC, gdutchak commented on src/partials/footer.html
> +        <p class="footer-copyright__text">@ All rights reserved, 2019</p>
замість собачки встав &#64; воно замінить символ і кожен браузер правильно відобразить

2022-05-13 22:09 UTC, gdutchak commented on src/sass/_footer.scss
> +    display: flex;
тут добре, але може спробуй марджинами відцентрувати, щоб потім так багато не перебивати на планшеті.

2022-05-14 09:57 UTC, Bykova-Kateryna commented on src/partials/footer.html
> +        <p class="footer-copyright__text">@ All rights reserved, 2019</p>
готово.

2022-05-14 09:57 UTC, Bykova-Kateryna commented on src/sass/_footer.scss
> +    display: flex;
готово.

2022-05-14 15:19 UTC, gdutchak approved these changes
все добре як на мене

2022-05-14 15:34 UTC, Bykova-Kateryna reviewed
.

2022-05-14 15:35 UTC, merged